source 'https://ruby.taobao.org'

gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'mysql2'
gem 'rake'
gem 'sinatra-contrib'
gem 'tilt', '~> 1.3.7'
gem 'unicorn'
gem 'redcarpet', :require => 'redcarpet'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'sinatra_more'
gem 'warden'
gem 'actionmailer'
gem 'sinatra-partial'
gem 'pygments.rb', :require => 'pygments'
gem 'json'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'qiniu', '~> 6.5.1'