development: &default
  sinatra: 'sinatra blog'
  site_title: "Michael Dai's Blog ~ Remember My Life"
  author: "Michael Dai"
  my_career: "Devops"
  location: "Shanghai, China"
  copyright: "Copyright © 2015 By Michael Dai. All rights reserved."

test: 
  <<: *default

production:
  <<: *default